using KaravanCoffeeWebAPI.Data;
using Microsoft.AspNetCore.Components.Server.Circuits;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.Extensions.Hosting;
using Org.BouncyCastle.Ocsp;
using System;
using System.IO.Pipelines;
using System.Net;
using System.Text.RegularExpressions;

namespace KaravanCoffeeWebAPI
{
    internal class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> builder)
        {
            builder.HasData(
                new Product
                {
                    ProductId = 1,
                    ProductCode = "PML-000001",
                    ProductName = "ANBESA BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 35.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 2,
                    ProductCode = "PML-000002",
                    ProductName = "ARADA BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 45.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {

                    ProductId = 3,
                    ProductCode = "PML-000003",
                    ProductName = "BEDELE BEER BIG",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 45.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 4,
                    ProductCode = "PML-000004",
                    ProductName = "BEDELE BEER SMALL",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 5,
                    ProductCode = "PML-000005",
                    ProductName = "CASTLE BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 6,
                    ProductCode = "PML-000006",
                    ProductName = "DASHEN BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 7,
                    ProductCode = "PML-000007",
                    ProductName = "HABESHA BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 8,
                    ProductCode = "PML-000008",
                    ProductName = "HARAR BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 9,
                    ProductCode = "PML-000009",
                    ProductName = "HEINEKEN BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 33.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 10,
                    ProductCode = "PML-000010",
                    ProductName = "MALTA",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 11,
                    ProductCode = "PML-000011",
                    ProductName = "SENQ BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 12,
                    ProductCode = "PML-000012",
                    ProductName = "ST GEORGE BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 13,
                    ProductCode = "PML-000013",
                    ProductName = "WALIA BEER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 1,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 43.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 14,
                    ProductCode = "PML-000014",
                    ProductName = "ACACIA DRY RED WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 15,
                    ProductCode = "PML-000015",
                    ProductName = "ACACIA DRY WHITE WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 16,
                    ProductCode = "PML-000016",
                    ProductName = "ACACIA ROSE WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 17,
                    ProductCode = "PML-000017",
                    ProductName = "ACACIA SWEET RED WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 18,
                    ProductCode = "PML-000018",
                    ProductName = "ACACIA SWEET WHITE WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 19,
                    ProductCode = "PML-000019",
                    ProductName = "AWASH TEKESHINO",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 350.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 20,
                    ProductCode = "PML-000020",
                    ProductName = "AWASH WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 250.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 21,
                    ProductCode = "PML-000021",
                    ProductName = "AXUMIT RED WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 350.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 22,
                    ProductCode = "PML-000022",
                    ProductName = "HENDEKE RED WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 250.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 23,
                    ProductCode = "PML-000023",
                    ProductName = "RIFT VALLEY MERLOT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 24,
                    ProductCode = "PML-000024",
                    ProductName = "RIFT VALLEY CHARDONNAY",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 480.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 25,
                    ProductCode = "PML-000025",
                    ProductName = "SHEBELE WHITE WINE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 250.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 26,
                    ProductCode = "PML-000026",
                    ProductName = "TEJ 1 LITER",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 2,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 280.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 27,
                    ProductCode = "PML-000027",
                    ProductName = "ST.GEORGE JAMBO DRAFT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 3,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 34.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 28,
                    ProductCode = "PML-000028",
                    ProductName = "ST.GEORGE SINGLE DRAFT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 3,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 23.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 29,
                    ProductCode = "PML-000029",
                    ProductName = "WALIA JAMBO DRAFT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 3,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 34.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 30,
                    ProductCode = "PML-000030",
                    ProductName = "WALIA SINGLE DRAFT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 3,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 23.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 31,
                    ProductCode = "PML-000031",
                    ProductName = "ABSOLUTE VODKA HALF BOTTLE(MEZO)",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 1200.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 32,
                    ProductCode = "PML-000032",
                    ProductName = "BLACK LABEL DOUBLE SHOT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 280.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 33,
                    ProductCode = "PML-000033",
                    ProductName = "CHIVAS REGAL DOUBLE SHOT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 150.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 34,
                    ProductCode = "PML-000034",
                    ProductName = "JACK  DANIELS HALF BOTTLE(MEZO)",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 4800.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 35,
                    ProductCode = "PML-000035",
                    ProductName = "OX CAFE",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 4200.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 36,
                    ProductCode = "PML-000036",
                    ProductName = "RED LABEL DOUBLE SHAT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 150.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 37,
                    ProductCode = "PML-000037",
                    ProductName = "SPECIAL GOLD LABEL WHISKY",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 5000.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 38,
                    ProductCode = "PML-000038",
                    ProductName = "STOLICHINYA DOUBLE SHAT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 165.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 39,
                    ProductCode = "PML-000039",
                    ProductName = "WHITE HORSE DOUBLE SHAT",
                    ProductDescription = "",
                    CategoryId = 1,
                    SubCategoryId = 4,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 75.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 40,
                    ProductCode = "PML-000040",
                    ProductName = "CHOCOLATE CHIP BISCUIT",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 5,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 75.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 41,
                    ProductCode = "PML-000041",
                    ProductName = "OATS BISCUTE",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 5,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 80.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 42,
                    ProductCode = "PML-000042",
                    ProductName = "VANILLA BISCUIT",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 5,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 60.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 43,
                    ProductCode = "PML-000043",
                    ProductName = "200GM BREAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 8.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 44,
                    ProductCode = "PML-000044",
                    ProductName = "2KG HABESHA BREAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 175.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 45,
                    ProductCode = "PML-000045",
                    ProductName = "300GM BERAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 15.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 46,
                    ProductCode = "PML-000046",
                    ProductName = "4KG HABESHA BREAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 350.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 47,
                    ProductCode = "PML-000047",
                    ProductName = "500GM BERAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 20.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 48,
                    ProductCode = "PML-000048",
                    ProductName = "NORMAL BREAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 5.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 49,
                    ProductCode = "PML-000049",
                    ProductName = "SLICE BREAD",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 6,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 30.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 50,
                    ProductCode = "PML-000050",
                    ProductName = "1KG COOKIES",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 7,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 51,
                    ProductCode = "PML-000051",
                    ProductName = "1/2KG COOKIES",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 7,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 200.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 52,
                    ProductCode = "PML-000052",
                    ProductName = "1/2KG PANETTONE",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 8,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 200.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 53,
                    ProductCode = "PML-000053",
                    ProductName = "APPLE PIE",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 9,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 95.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 54,
                    ProductCode = "PML-000054",
                    ProductName = "CHOCOLATE TART",
                    ProductDescription = "",
                    CategoryId = 2,
                    SubCategoryId = 9,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 85.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 55,
                    ProductCode = "PML-000055",
                    ProductName = "BLACK FOREST CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 80.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 56,
                    ProductCode = "PML-000056",
                    ProductName = "BLUE BERRY CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 100.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 57,
                    ProductCode = "PML-000057",
                    ProductName = "BOXEGNA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 90.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 58,
                    ProductCode = "PML-000058",
                    ProductName = "BRONZE CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 59,
                    ProductCode = "PML-000059",
                    ProductName = "CARAMEL CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 95.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 60,
                    ProductCode = "PML-000060",
                    ProductName = "CHOCOLATE BUTTER CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 61,
                    ProductCode = "PML-000061",
                    ProductName = "CHOCOLATE TRUFFLE CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 62,
                    ProductCode = "PML-000062",
                    ProductName = "CUP CAKE WITH CREAM",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 90.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 63,
                    ProductCode = "PML-000063",
                    ProductName = "CUP CAKE WITH FONDANT",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 120.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 64,
                    ProductCode = "PML-000064",
                    ProductName = "DESSERT CUPS",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 70.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 65,
                    ProductCode = "PML-000065",
                    ProductName = "DOUBLE CHOCOLATE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 107.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 66,
                    ProductCode = "PML-000066",
                    ProductName = "EIFFEL TOWER BOXEGNA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 970.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 67,
                    ProductCode = "PML-000067",
                    ProductName = "FASTING CREAM CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 80.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 68,
                    ProductCode = "PML-000068",
                    ProductName = "HONEY CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 69,
                    ProductCode = "PML-000069",
                    ProductName = "KARAVAN PARTY MIX",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 450.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 70,
                    ProductCode = "PML-000070",
                    ProductName = "LEMON CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 71,
                    ProductCode = "PML-000071",
                    ProductName = "MILLEFEUILLE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 80.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 72,
                    ProductCode = "PML-000072",
                    ProductName = "OPERA CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 109.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 73,
                    ProductCode = "PML-000073",
                    ProductName = "ORANGE CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 100.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 74,
                    ProductCode = "PML-000074",
                    ProductName = "OREO CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 100.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 75,
                    ProductCode = "PML-000075",
                    ProductName = "PURPEL CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 76,
                    ProductCode = "PML-000076",
                    ProductName = "RED VELVET CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 105.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 77,
                    ProductCode = "PML-000077",
                    ProductName = "STRAWBERRY DREAM CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 130.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 78,
                    ProductCode = "PML-000078",
                    ProductName = "STRAWBERRY GLAZE CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 100.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 79,
                    ProductCode = "PML-000079",
                    ProductName = "TIRAMISU CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 95.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 80,
                    ProductCode = "PML-000080",
                    ProductName = "VANILLA CREAM CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 75.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                new Product
                {
                    ProductId = 81,
                    ProductCode = "PML-000081",
                    ProductName = "WHITE FOREST CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 10,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 75.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                },
                 new Product
                 {
                     ProductId = 82,
                     ProductCode = "PML-000082",
                     ProductName = "BOMBOLINO",
                     ProductDescription = "",
                     CategoryId = 3,
                     SubCategoryId = 11,
                     ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                     UnitPrice = 50.00,
                     ProductPoint = 0,
                     Rating = 5,
                     AverageQueueDay = 0,
                     AverageQueueTime = TimeOnly.Parse("00:00:00"),
                     Discount = 0,
                     Tag = "",
                     Active = false,
                     Orderable = false
                 },
                                new Product
                                {
                                    ProductId = 83,
                                    ProductCode = "PML-000083",
                                    ProductName = "CHOCOLATE CROISSANT",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 80.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 84,
                                    ProductCode = "PML-000084",
                                    ProductName = "CHOCOLATE MUFFIN",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 55.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 85,
                                    ProductCode = "PML-000085",
                                    ProductName = "CROISSANT",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 70.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 86,
                                    ProductCode = "PML-000086",
                                    ProductName = "DOUGNUTS",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 55.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 87,
                                    ProductCode = "PML-000087",
                                    ProductName = "ENGLISH CAKE",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 55.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 88,
                                    ProductCode = "PML-000088",
                                    ProductName = "FASTING CROISSANT",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 60.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 89,
                                    ProductCode = "PML-000089",
                                    ProductName = "FASTING ENGLISH CAKE",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 50.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 90,
                                    ProductCode = "PML-000090",
                                    ProductName = "FASTING VENUS",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 40.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 91,
                                    ProductCode = "PML-000091",
                                    ProductName = "FRUIT TART",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 80.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 92,
                                    ProductCode = "PML-000092",
                                    ProductName = "FULL MULMUL",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 400.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 93,
                                    ProductCode = "PML-000093",
                                    ProductName = "HALF MULMUL",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 200.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 94,
                                    ProductCode = "PML-000094",
                                    ProductName = "VANILLA MUFFINE",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 90.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }, new Product
                                {
                                    ProductId = 95,
                                    ProductCode = "PML-000095",
                                    ProductName = "VENUS CAKE",
                                    ProductDescription = "",
                                    CategoryId = 3,
                                    SubCategoryId = 11,
                                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                                    UnitPrice = 40.00,
                                    ProductPoint = 0,
                                    Rating = 5,
                                    AverageQueueDay = 0,
                                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                                    Discount = 0,
                                    Tag = "",
                                    Active = false,
                                    Orderable = false
                                }
                , new Product
                {
                    ProductId = 96,
                    ProductCode = "PML-000096",
                    ProductName = "ZEBIB CAKE",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 11,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 55.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 97,
                    ProductCode = "PML-000097",
                    ProductName = "2KG BLACK FOREST TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 1700.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 98,
                    ProductCode = "PML-000098",
                    ProductName = "2KG CARAMEL TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 1900.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 99,
                    ProductCode = "PML-000099",
                    ProductName = "2KG CHOCOLATE TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2100.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 100,
                    ProductCode = "PML-0000100",
                    ProductName = "2KG FASTING TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 1700.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 102,
                    ProductCode = "PML-0000102",
                    ProductName = "2KG FONDANT TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2900.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 103,
                    ProductCode = "PML-0000103",
                    ProductName = "2KG OPERA TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 104,
                    ProductCode = "PML-0000104",
                    ProductName = "2KG RED VALET TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 105,
                    ProductCode = "PML-0000105",
                    ProductName = "2KG TIRAMISU TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 1900.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 106,
                    ProductCode = "PML-0000106",
                    ProductName = "2KG WHITE FOREST TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 1700.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 107,
                    ProductCode = "PML-0000107",
                    ProductName = "3KG BLACK FOREST TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2500.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 108,
                    ProductCode = "PML-0000108",
                    ProductName = "3KG CARAMEL TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2700.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 109,
                    ProductCode = "PML-0000109",
                    ProductName = "3KG CHOCOLATE TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 3200.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 110,
                    ProductCode = "PML-0000110",
                    ProductName = "3KG FASTING WHITE FOREST TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2500.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 111,
                    ProductCode = "PML-0000111",
                    ProductName = "3KG FONDANT TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 4300.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 112,
                    ProductCode = "PML-0000112",
                    ProductName = "3KG OPERA TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 3400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 113,
                    ProductCode = "PML-0000113",
                    ProductName = "BOMBOLINO",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 2500.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 114,
                    ProductCode = "PML-0000114",
                    ProductName = "4KG BLACK FOREST TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 3400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 115,
                    ProductCode = "PML-0000115",
                    ProductName = "4KG CARAMEL TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 3600.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 116,
                    ProductCode = "PML-0000116",
                    ProductName = "4KG FASTING WHITE FOREST TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 3400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 117,
                    ProductCode = "PML-0000117",
                    ProductName = "4KG FONDANT TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 5300.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }, new Product
                {
                    ProductId = 118,
                    ProductCode = "PML-0000118",
                    ProductName = "4KG OPERA TORTA",
                    ProductDescription = "",
                    CategoryId = 3,
                    SubCategoryId = 12,
                    ImagePath = "http://karavancoffee1-001-site1.atempurl.com/Images/Products/NoPicture.jpg",
                    UnitPrice = 4400.00,
                    ProductPoint = 0,
                    Rating = 5,
                    AverageQueueDay = 0,
                    AverageQueueTime = TimeOnly.Parse("00:00:00"),
                    Discount = 0,
                    Tag = "",
                    Active = false,
                    Orderable = false
                }
                );
        }
    }
}