// <auto-generated />
using System;
using KaravanCoffeeWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaravanCoffeeWebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221227082839_Database_Created")]
    partial class DatabaseCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BranchAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("BranchName")
                        .HasColumnType("longtext");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryDescription = "",
                            CategoryName = "ALCOHOLIC BEVERAGES",
                            ImagePath = ""
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryDescription = "",
                            CategoryName = "Cake",
                            ImagePath = ""
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryDescription = "",
                            CategoryName = "Bakery",
                            ImagePath = ""
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryDescription = "",
                            CategoryName = "Ice Cream",
                            ImagePath = ""
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryDescription = "",
                            CategoryName = "Habeshan Dish",
                            ImagePath = ""
                        });
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.LoyalityDetail", b =>
                {
                    b.Property<int>("LoyalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("LoyalityPoint")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("LoyalityId");

                    b.HasIndex("BranchId");

                    b.HasIndex("OrderDetailId");

                    b.ToTable("LoyalityDetail");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveredBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderType")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("datetime");

                    b.Property<int>("RedeemedPoints")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(95)");

                    b.Property<byte>("Void")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("OrderId");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<double>("SubTotal")
                        .HasColumnType("double");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("MainIngredients")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductPoint")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<bool>("RequireExtra")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TotalOrdered")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000001",
                            ProductDescription = "",
                            ProductName = "ANBESA BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 35.0
                        },
                        new
                        {
                            ProductId = 2,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000002",
                            ProductDescription = "",
                            ProductName = "ARADA BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 45.0
                        },
                        new
                        {
                            ProductId = 3,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000003",
                            ProductDescription = "",
                            ProductName = "BEDELE BEER BIG",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 45.0
                        },
                        new
                        {
                            ProductId = 4,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000004",
                            ProductDescription = "",
                            ProductName = "BEDELE BEER SMALL",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 5,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000005",
                            ProductDescription = "",
                            ProductName = "CASTLE BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 6,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000006",
                            ProductDescription = "",
                            ProductName = "DASHEN BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 7,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000007",
                            ProductDescription = "",
                            ProductName = "HABESHA BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 8,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000008",
                            ProductDescription = "",
                            ProductName = "HARAR BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 9,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000009",
                            ProductDescription = "",
                            ProductName = "HEINEKEN BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 33.0
                        },
                        new
                        {
                            ProductId = 10,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000010",
                            ProductDescription = "",
                            ProductName = "MALTA",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 11,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000011",
                            ProductDescription = "",
                            ProductName = "SENQ BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 12,
                            Active = false,
                            CategoryId = 1,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000012",
                            ProductDescription = "",
                            ProductName = "ST GEORGE BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        },
                        new
                        {
                            ProductId = 13,
                            Active = false,
                            CategoryId = 2,
                            Discount = 0.0,
                            ImagePath = "",
                            MainIngredients = "",
                            ProductCode = "PML-000013",
                            ProductDescription = "",
                            ProductName = "WALIA BEER",
                            ProductPoint = 0,
                            Rating = 5.0,
                            RequireExtra = false,
                            SubCategoryId = 1,
                            TotalOrdered = 0,
                            UnitPrice = 43.0
                        });
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.ProductAvailability", b =>
                {
                    b.Property<int>("ProductAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("MaxThreshold")
                        .HasColumnType("int");

                    b.Property<int>("MinThreshold")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductAvailabilityId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAvailability");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("SubCategoryDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("SubCategoryName")
                        .HasColumnType("longtext");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            SubCategoryId = 1,
                            CategoryId = 1,
                            ImagePath = "",
                            SubCategoryDescription = "",
                            SubCategoryName = "ALCOHOLIC BEVERAGES"
                        },
                        new
                        {
                            SubCategoryId = 2,
                            CategoryId = 1,
                            ImagePath = "",
                            SubCategoryDescription = "",
                            SubCategoryName = "Cake"
                        },
                        new
                        {
                            SubCategoryId = 3,
                            CategoryId = 1,
                            ImagePath = "",
                            SubCategoryDescription = "",
                            SubCategoryName = "Bakery"
                        },
                        new
                        {
                            SubCategoryId = 4,
                            CategoryId = 1,
                            ImagePath = "",
                            SubCategoryDescription = "",
                            SubCategoryName = "Ice Cream"
                        },
                        new
                        {
                            SubCategoryId = 5,
                            CategoryId = 1,
                            ImagePath = "",
                            SubCategoryDescription = "",
                            SubCategoryName = "Habeshan Dish"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0701b11d-9e92-491f-acc0-062270295060",
                            ConcurrencyStamp = "a322e993-4bb9-42c0-88f0-7798c1ecdad6",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "5e806eb5-8303-41d1-a20d-82d73b7f4908",
                            ConcurrencyStamp = "eb6795a7-f51a-4597-a796-0463307fcd2e",
                            Name = "Branch Admin",
                            NormalizedName = "BRANCH ADMIN"
                        },
                        new
                        {
                            Id = "73000fb6-a591-45b3-a2ca-32cc573f0574",
                            ConcurrencyStamp = "63971f9b-c6ad-49f9-b10f-8f61da8fc412",
                            Name = "System Admin",
                            NormalizedName = "SYSTEM ADMIN"
                        },
                        new
                        {
                            Id = "0e60e92e-118d-4e98-a0e5-5a169e5ac7ef",
                            ConcurrencyStamp = "c1d01487-d284-4daa-ab0d-1126462959ce",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(95)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(95)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.LoyalityDetail", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaravanCoffeeWebAPI.Data.OrderDetail", "OrderDetail")
                        .WithMany()
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Order", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaravanCoffeeWebAPI.Data.Person", "Person")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.OrderDetail", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaravanCoffeeWebAPI.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Product", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaravanCoffeeWebAPI.Data.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.ProductAvailability", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaravanCoffeeWebAPI.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.SubCategory", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KaravanCoffeeWebAPI.Data.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KaravanCoffeeWebAPI.Data.Person", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KaravanCoffeeWebAPI.Data.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
